import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import StoryblokProvider from "@/components/StoryBlokProvider"
import { getStoryblokApi } from "@/lib/storyblok"
import { StoryblokServerComponent } from "@storyblok/react/rsc"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const storyblokApi = getStoryblokApi()

  const { data } = await storyblokApi.get("cdn/stories/config", {
    version: "draft",
    resolve_links: "url",
  })

  const config = data.story.content
  const headerBlok = config.header?.[0]
  const footerBlok = config.footer?.[0]

  return (
    <StoryblokProvider>
      {headerBlok && <StoryblokServerComponent blok={headerBlok} />}
      <html
        lang="en"
        className={`bg-gray-200  h-full antialiased overflow-y-scroll`}
      >
        <body className="bg-white py-1 px-0.5 rounded-2xl container mx-auto my-3 flex flex-col">
          <div className="container max-w-[90%] mx-auto">{children}</div>
        </body>
      </html>
      {footerBlok && <StoryblokServerComponent blok={footerBlok} />}
    </StoryblokProvider>
  )
}
